### ISSUE TITLE
Hi, bro, I'm have been building PFNN demo for two days! but still failed. OMG! So, how to use your project to build?

### ISSUE THREAD

**Issue by youngyangk** [ldm0/pfnn_easy_to_use#1]

**Comment by ldm0** [comment]
Any error log?

**Comment by youngyangk** [comment]
The log is so long!  I'm going to give up. I want to try your method.

**Comment by ldm0** [comment]
Give it a try!

**Comment by ldm0** [comment]
Just use the CMakeLists.txt

**Comment by youngyangk** [comment]
Hi, Why I can't use handle to control character using your project to compile？

**Comment by ldm0** [comment]
> Hi, Why I can't use handle to control character using your project to compile？

Hm, that's because I didn't have a gamepad at that time. So I tweaked the code for enabling keyboard control and disabling gamepad control.

**Comment by ldm0** [comment]
Fixed.
